apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "votre_nouveau_mot_de_passe"
        - name: MYSQL_DATABASE
          value: "flask_dev"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ton-utilisateur/app-flask:v2  # Remplacez par l'image de votre application Flask
        ports:
        - containerPort: 5000
