apiVersion: v1
kind: Namespace
metadata:
  name: appnamespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
  namespace: appnamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appdevops
  template:
    metadata:
      labels:
        app: appdevops
    spec:
      containers:
        - name: devopsexam
          image: dinho/devopsexam:latest # Remplacez par votre image
          ports:
            - containerPort: 8081
          env:
            - name: URL
              value: "mysql://root:root@db-service:5432/db" # Configuration pour la base de données
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbdeployment
  namespace: appnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysqlcontainer
          image: mysql:latest
          ports:
            - containerPort: 5432
          env:
            - name: USER
              value: "root"
            - name: PASSWORD
              value: "root"
            - name: DB
              value: "db"
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
  namespace: appnamespace
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
  namespace: appnamespace
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

